import type { Metadata } from "next";
import { Navbar } from "@/components/navbar";
import { Footer } from "@/components/footer";
import { LEGAL_EFFECTIVE_DATE, LEGAL_LAST_UPDATED, LEGAL_OWNER } from "@/lib/legal";

export const metadata: Metadata = {
  title: "Terms and Conditions",
  description: "Read the Stackin terms and conditions.",
  alternates: {
    canonical: "/terms",
  },
};

const termsSections = [
  {
    title: "1. Acceptance of These Terms",
    paragraphs: [
      "These Terms and Conditions govern your access to and use of Stackin and any related websites, mobile applications, software, content, and services we provide. By clicking to accept, creating an account, downloading, accessing, subscribing to, or using Stackin, you agree to these terms. If you do not agree, do not use the app.",
    ],
  },
  {
    title: "2. Eligibility and Authority",
    paragraphs: [
      "You must be at least 18 years old and legally able to enter into a binding agreement to use Stackin. If you use Stackin on behalf of a business, employer, or other entity, you represent that you have authority to bind that entity to these terms.",
    ],
  },
  {
    title: "3. What Stackin Does",
    paragraphs: [
      "Stackin is a financial organization and income-tracking tool. Depending on your plan and device, features may include work-entry tracking, W-2 and independent income logging, expense tracking, receipt capture, OCR-assisted data extraction, profit and loss summaries, paycheck and withholding estimates, pay stub generation, reminders, workspace management, notifications, and premium features.",
      "Stackin is designed to help you organize information. It is not represented as an official bookkeeping system of record, payroll processor, payroll administrator, employer, employer-of-record, consumer reporting agency, bank, lender, money transmitter, tax filing service, tax preparation service, or government reporting platform.",
    ],
  },
  {
    title: "4. No Tax, Legal, Accounting, Payroll, or Financial Advice",
    paragraphs: [
      "Stackin does not provide tax, legal, accounting, payroll, audit, investment, or financial advice, and no fiduciary, advisory, attorney-client, accountant-client, or similar professional relationship is created by your use of the app.",
      "Any estimates, categorizations, summaries, paycheck calculations, withholding projections, pay stubs, tax-related outputs, or other generated materials are for informational and organizational purposes only. You are responsible for getting advice from qualified professionals before relying on any output for taxes, payroll, accounting, wage-and-hour compliance, worker classification, employment verification, lending, housing, immigration, public benefits, insurance, or legal purposes.",
    ],
  },
  {
    title: "5. No Guarantee of Accuracy or Acceptance",
    paragraphs: [
      "Stackin depends on information from you, your device, and in some cases third-party services. You are solely responsible for ensuring your entries, imported records, expense details, rates, dates, tax profile information, and other inputs are accurate, complete, lawful, and current.",
      "You are also solely responsible for reviewing and verifying all outputs before using them. We do not guarantee that any estimate, calculation, category suggestion, report, reminder, or generated record will be accurate, complete, current, accepted by any employer, worker, accountant, lender, insurer, government agency, court, or other third party, or suitable for your intended purpose.",
    ],
  },
  {
    title: "6. Generated Records and Reports",
    paragraphs: [
      "Any pay stubs, summaries, reports, statements, profit and loss outputs, receipt extractions, tax estimates, or similar materials generated by Stackin are based on user-supplied or third-party-supplied data and app logic. Unless we expressly state otherwise in writing, they are not official payroll records, certified accounting statements, audited financial statements, tax returns, government filings, or legal documents.",
      "You may not use Stackin to create, submit, distribute, or present false, misleading, unauthorized, or deceptively altered documents or to misrepresent your identity, employment status, income, expenses, tax position, or business records.",
    ],
  },
  {
    title: "7. Automated Features, OCR, and Suggestions",
    paragraphs: [
      "Some Stackin features may use automation, OCR, rules, heuristics, machine learning, or similar technologies to extract, suggest, classify, summarize, or generate information. These features are provided for convenience only and may make mistakes, omit information, or produce misleading or incomplete results.",
      "You remain responsible for checking and approving anything created or suggested by those features before relying on it.",
    ],
  },
  {
    title: "8. Device Permissions, Notifications, and Location-Based Features",
    paragraphs: [
      "Certain features may request access to notifications, camera, photos, location, or other device permissions in order to provide receipt capture, reminders, geofence alerts, and similar functionality.",
      "If you enable those features, you authorize Stackin to use the relevant permissions for those purposes. You acknowledge that reminders and location-based features may be delayed, inaccurate, incomplete, duplicated, or unavailable due to device settings, battery restrictions, operating system behavior, connectivity, third-party platform limitations, or disabled permissions. These features are convenience tools only and must not be relied on for safety-critical, payroll-critical, tax-critical, compliance-critical, or legal purposes.",
    ],
  },
  {
    title: "9. Offline Use, Local Storage, and Sync",
    paragraphs: [
      "Some Stackin features may support caching, offline entry, delayed synchronization, or queued actions. Because of that, information shown on your device may temporarily differ from server data, and sync actions may be delayed, duplicated, partially applied, or fail altogether.",
      "You are responsible for confirming that important data has been entered, saved, and synchronized properly.",
      "You should keep your own backup copies of any information you consider important, including records you may need for tax, payroll, accounting, compliance, employment, or legal purposes.",
    ],
  },
  {
    title: "10. Accounts and Security",
    paragraphs: [
      "You are responsible for maintaining accurate account information, safeguarding your login credentials, and all activity that occurs under your account. You must notify us promptly if you suspect unauthorized use, credential compromise, or a security issue affecting your account or device. You may not share your account in a way that bypasses plan limits, security controls, or authorized-use restrictions.",
    ],
  },
  {
    title: "11. Limited License",
    paragraphs: [
      "Subject to your compliance with these terms, we grant you a limited, personal, non-exclusive, non-transferable, non-sublicensable, revocable license to use Stackin for your internal lawful use during your authorized access period. Stackin is licensed, not sold.",
    ],
  },
  {
    title: "12. Subscriptions, Billing, Trials, and App Stores",
    paragraphs: [
      "Certain features may require a paid subscription or paid upgrade. By subscribing, you authorize the charges, taxes, and renewal terms shown to you at purchase. Pricing, usage limits, feature availability, and renewal terms may vary by plan and may change prospectively as permitted by law.",
      "If your subscription renews automatically, it will continue until canceled in the applicable cancellation flow. Unless required by law or expressly stated by us, fees are non-refundable once charged, and canceling does not retroactively refund the current billing period. If you subscribe through Apple, Google, or another marketplace, billing and cancellation may be handled by that provider and may also be subject to its separate terms.",
      "Specific pricing, trial, renewal, cancellation, refund, and promotional terms shown to you at checkout, in your account settings, or in the applicable marketplace purchase flow will control to the extent they conflict with these general terms.",
    ],
  },
  {
    title: "13. App Stores and Device Platforms",
    paragraphs: [
      "If you download or access Stackin through Apple's App Store, Google Play, or another app marketplace or device platform, you acknowledge that the platform provider is not a party to these terms and is not responsible for Stackin, its content, maintenance, support, or claims relating to Stackin, except to the extent required by applicable law or mandatory platform terms.",
      "Your use of Stackin must also comply with the applicable platform's usage rules, terms, and technical limitations. To the extent permitted by law, applicable platform providers are third-party beneficiaries of this section and may enforce it against you.",
    ],
  },
  {
    title: "14. Privacy and Electronic Communications",
    paragraphs: [
      "Your use of Stackin is also subject to our Privacy Policy. By using the app, you consent to the collection, use, storage, and processing of information as described in that policy and as reasonably necessary to operate, secure, support, maintain, and improve Stackin.",
      "You also agree that we may send you service-related notices and other legally required communications electronically, including through the app, by email, or by other reasonable digital means. You are responsible for keeping your email address and other contact information current.",
    ],
  },
  {
    title: "15. Your Content and Data",
    paragraphs: [
      "As between you and Optivium AI Solutions LLC, you retain ownership of the information and content you submit to Stackin. You grant us a worldwide, non-exclusive, royalty-free license to host, store, reproduce, process, format, transmit, and use that content only as necessary to operate, provide, secure, troubleshoot, support, improve, and enforce Stackin and these terms.",
      "You represent that you have the rights, notices, and permissions needed to submit any data or content you provide, including information about other people, and that your submission and our permitted use of it will not violate any law or third-party rights.",
    ],
  },
  {
    title: "16. Feedback",
    paragraphs: [
      "If you send us suggestions, ideas, requests, or feedback about Stackin, you allow us to use that feedback without restriction or compensation to you.",
    ],
  },
  {
    title: "17. Prohibited Uses",
    paragraphs: [
      "You may not use Stackin for any unlawful, fraudulent, deceptive, abusive, harmful, or unauthorized purpose. This includes attempting to access another user's data, interfering with app operations, submitting false information, reverse engineering the app, bypassing security or usage limits, reselling unauthorized access, scraping data, uploading malicious code, infringing intellectual property rights, or using Stackin in violation of tax, payroll, employment, privacy, consumer protection, sanctions, export, or financial recordkeeping laws. It also includes using Stackin to fabricate, falsify, or deceptively alter pay stubs, income records, receipts, tax-related information, or other documents, or to mislead employers, workers, lenders, landlords, insurers, regulators, courts, or government agencies.",
    ],
  },
  {
    title: "18. Third-Party Services and Content",
    paragraphs: [
      "Stackin may rely on or integrate with third-party services such as authentication, cloud hosting, notifications, app stores, analytics, payment processing, maps, OCR, or other service providers. We are not responsible for the availability, accuracy, security, legality, or terms of any third-party services, content, or products. Those providers may change, suspend, or discontinue their services at any time.",
    ],
  },
  {
    title: "19. Beta or Experimental Features",
    paragraphs: [
      "We may offer beta, preview, early access, or experimental features from time to time. Those features may be incomplete, unstable, changed, or removed at any time and are provided on an as-is basis with no special guarantees.",
    ],
  },
  {
    title: "20. Service Availability and Changes",
    paragraphs: [
      "We may modify, improve, restrict, suspend, or discontinue all or part of Stackin at any time, with or without notice, to the extent permitted by law. We do not guarantee uninterrupted availability, continued support for any feature, or that Stackin will be error-free, secure, or compatible with every device or operating system version.",
    ],
  },
  {
    title: "21. Suspension, Termination, and Account Deletion",
    paragraphs: [
      "We may suspend or terminate your access to Stackin, with or without notice, if we believe you violated these terms, created legal, financial, or security risk, failed to pay required fees, or used the app in a way that may harm us, other users, or third parties.",
      "You may request account deletion, subject to identity verification and any applicable legal, contractual, technical, fraud-prevention, billing, tax, security, or record-retention requirements. Deleting the app from your device does not necessarily cancel a subscription or delete your account or stored data.",
    ],
  },
  {
    title: "22. Intellectual Property",
    paragraphs: [
      "Stackin, including its software, code, design, branding, interfaces, text, graphics, underlying technology, and related intellectual property, is owned by Optivium AI Solutions LLC or its licensors and is protected by law. Except for the limited rights expressly granted in these terms, no rights are granted to you.",
    ],
  },
  {
    title: "23. Disclaimer of Warranties",
    paragraphs: [
      "TO THE MAXIMUM EXTENT PERMITTED BY LAW, STACKIN IS PROVIDED \"AS IS\" AND \"AS AVAILABLE.\" WE DISCLAIM ALL WARRANTIES, WHETHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, INCLUDING IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, NON-INFRINGEMENT, ACCURACY, SECURITY, AVAILABILITY, AND QUIET ENJOYMENT.",
      "WITHOUT LIMITING THE FOREGOING, WE DO NOT WARRANT THAT ANY DATA, ESTIMATE, CLASSIFICATION, GENERATED DOCUMENT, REMINDER, RECEIPT EXTRACTION, LOCATION-BASED FEATURE, SUBSCRIPTION FEATURE, SYNC PROCESS, OR THIRD-PARTY INTEGRATION WILL BE ACCURATE, COMPLETE, CURRENT, ACCEPTED BY THIRD PARTIES, ERROR-FREE, SECURE, OR UNINTERRUPTED.",
    ],
  },
  {
    title: "24. Limitation of Liability",
    paragraphs: [
      "TO THE MAXIMUM EXTENT PERMITTED BY LAW, OPTIVIUM AI SOLUTIONS LLC AND ITS AFFILIATES, OFFICERS, MEMBERS, EMPLOYEES, CONTRACTORS, LICENSORS, AND SERVICE PROVIDERS WILL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES, OR FOR ANY LOSS OF PROFITS, REVENUE, SAVINGS, TAX BENEFITS, BUSINESS OPPORTUNITY, GOODWILL, DATA, OR BUSINESS INTERRUPTION, ARISING OUT OF OR RELATING TO STACKIN OR THESE TERMS, WHETHER IN CONTRACT, TORT, NEGLIGENCE, STRICT LIABILITY, STATUTE, OR ANY OTHER LEGAL THEORY, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.",
      "TO THE MAXIMUM EXTENT PERMITTED BY LAW, OUR TOTAL AGGREGATE LIABILITY FOR ALL CLAIMS ARISING OUT OF OR RELATING TO STACKIN OR THESE TERMS WILL NOT EXCEED THE GREATER OF THE AMOUNT YOU PAID TO US FOR STACKIN IN THE TWELVE MONTHS BEFORE THE EVENT GIVING RISE TO THE CLAIM OR USD $100.",
    ],
  },
  {
    title: "25. Indemnification",
    paragraphs: [
      "You agree to defend, indemnify, and hold harmless Optivium AI Solutions LLC and its affiliates, officers, members, employees, contractors, licensors, and service providers from and against any claims, liabilities, damages, losses, judgments, fines, penalties, costs, and expenses, including reasonable attorneys' fees, arising out of or related to your use of Stackin, your data, your content, your violation of these terms, or your violation of any law or third-party rights.",
    ],
  },
  {
    title: "26. Dispute Resolution; Arbitration; Class Action Waiver",
    paragraphs: [
      "To the maximum extent permitted by law, you and Optivium AI Solutions LLC agree to try to resolve disputes informally first. Except for disputes that qualify for small claims court, disputes that are not resolved informally will be resolved on an individual basis through binding arbitration instead of in court before a judge or jury. The Federal Arbitration Act and federal arbitration law govern the interpretation and enforcement of this section. Unless applicable law requires otherwise, the arbitration will be administered by the American Arbitration Association under its applicable consumer arbitration rules, as modified by these terms.",
      "You and we each waive any right to participate in a class action, class arbitration, private attorney general action, or other representative proceeding. If applicable law does not allow arbitration or class action waiver for a particular claim, that claim will proceed only to the extent required by law and the remainder of this section will still apply as far as permitted.",
      "Nothing in this section prevents either party from seeking qualifying small claims relief or temporary or preliminary injunctive relief in a court of competent jurisdiction to protect intellectual property, confidential information, security, or data pending completion of arbitration.",
    ],
  },
  {
    title: "27. Governing Law",
    paragraphs: [
      "Except to the extent preempted by applicable federal law or otherwise required by mandatory law, these terms are governed by the laws of the state in which Optivium AI Solutions LLC is organized, without regard to conflict-of-law rules. If a dispute is permitted to proceed in court rather than arbitration, you and we consent to the personal jurisdiction of the state and federal courts located in that state, subject to any non-waivable rights you may have under applicable law.",
    ],
  },
  {
    title: "28. Updates to These Terms",
    paragraphs: [
      "We may update these terms from time to time. If we make material changes, we may provide notice by updating the date above, posting updated terms in the app, emailing you, or using other reasonable means. Your continued use of Stackin after updated terms become effective constitutes acceptance of the revised terms.",
    ],
  },
  {
    title: "29. Miscellaneous",
    paragraphs: [
      "These terms, together with any incorporated policies or additional terms presented to you, form the entire agreement between you and us regarding Stackin. If any provision is held unenforceable, the remaining provisions will remain in effect. Our failure to enforce any provision is not a waiver. We may assign these terms in connection with a merger, acquisition, corporate reorganization, or sale of assets. Except as expressly stated in these terms, there are no third-party beneficiaries. Sections that by their nature should survive termination will survive termination.",
    ],
  },
  {
    title: "30. Contact Information",
    paragraphs: [
      "Optivium AI Solutions LLC",
      "For support, legal notices, or terms-related questions, please use the contact information provided through Stackin or our official business contact channels, including the contact information we make available at stackin-app.com.",
    ],
  },
] as const;

const closingStatement =
  "By using Stackin, you acknowledge that you have read and understood these Terms and Conditions, that Stackin provides organizational and informational tools only, and that you are responsible for reviewing and verifying any output before relying on it.";

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-background">
      <Navbar />
      <section className="mx-auto max-w-4xl px-4 pb-24 pt-32 sm:px-6 lg:px-8">
        <div className="rounded-3xl border border-border bg-card/50 p-8 shadow-sm sm:p-12">
          <p className="text-sm font-medium uppercase tracking-[0.24em] text-primary">
            Terms
          </p>
          <h1 className="mt-4 text-4xl font-semibold tracking-tight text-foreground">
            Terms and Conditions
          </h1>
          <p className="mt-4 text-base leading-7 text-muted-foreground">
            These terms govern your access to and use of Stackin and related services.
          </p>

          <section className="mt-8 rounded-2xl border border-border bg-background/70 p-5 text-sm leading-7 text-muted-foreground">
            <h2 className="text-lg font-semibold text-foreground">Terms and Conditions</h2>
            <p>
              <strong className="text-foreground">Effective Date:</strong> {LEGAL_EFFECTIVE_DATE}
            </p>
            <p>
              <strong className="text-foreground">Last Updated:</strong> {LEGAL_LAST_UPDATED}
            </p>
            <p>
              <strong className="text-foreground">Owner:</strong> {LEGAL_OWNER}
            </p>
          </section>

          <div className="mt-10 space-y-8 text-sm leading-7 text-muted-foreground sm:text-base">
            {termsSections.map((section) => (
              <section key={section.title}>
                <h2 className="text-xl font-semibold text-foreground">{section.title}</h2>
                {section.paragraphs.map((paragraph) => (
                  <p key={paragraph} className="mt-3">
                    {paragraph}
                  </p>
                ))}
              </section>
            ))}

            <section>
              <p className="italic text-foreground/90">{closingStatement}</p>
            </section>
          </div>
        </div>
      </section>
      <Footer />
    </main>
  );
}
